<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>

    <PackageId>ProcessMemory</PackageId>
    <Version>1.4.0</Version>
    <Authors>mat1jaczyyy</Authors>
    <Title>ProcessMemory</Title>
    <Description>A Windows x64 process memory reader and writer for .NET Framework.</Description>
    <PackageTags>process memory read write ram windows x64</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/mat1jaczyyy/ProcessMemory</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mat1jaczyyy/ProcessMemory.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>Makes process reads non-invasive, requires complete reads, and adds wildcard signature scanning.</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
